name: Code Scanning

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions: write-all

jobs:
  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: GitLeaks Scanning
        uses: gitleaks/gitleaks-action@v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trufflehog Scanning
        uses: trufflesecurity/trufflehog@v3.94.1
        with:
          extra_args: --results=verified,unknown

  codeql-scanning:
    name: CodeQL Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: CodeQL Initialize
        uses: github/codeql-action/init@v4.35.1
        with:
          languages: rust

      - name: CodeQL Analyze
        uses: github/codeql-action/analyze@v4.35.1
