name: Pre-commit auto-update

on:
  # every day at midnight
  schedule:
    - cron: "0 0 * * *"
  # manually trigger a workflow_dispatch event
  workflow_dispatch:

permissions: write-all

jobs:
  auto-update:
    name: Auto Update Pre-Commit Hooks
    runs-on: ubuntu-latest

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Pre-Commit
        run: |
          uv tool install pre-commit
          uv tool run pre-commit autoupdate -j 8
          uv tool run pre-commit run -a

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v8.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: chore/pre-commit-hooks  # push from this branch
          title: "chore: Update pre-commit hooks"
          body: "Update versions of pre-commit hooks to latest version."
          commit-message: "chore: update pre-commit hooks"
          delete-branch: true

      - name: Auto Merge Pull Request
        continue-on-error: true
        if: ${{ steps.create-pr.outputs.pull-request-url }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --squash --auto --delete-branch "${{ steps.create-pr.outputs.pull-request-url }}"
